//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputActions/PlayerController/MobalInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MobalInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MobalInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MobalInputActions"",
    ""maps"": [
        {
            ""name"": ""GameplayMap"",
            ""id"": ""21d17648-e369-4513-8c2d-503197b66d38"",
            ""actions"": [
                {
                    ""name"": ""SelectMovePosition"",
                    ""type"": ""Button"",
                    ""id"": ""a4b044a7-da29-4cdd-bbc0-28d3f754b714"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AoeAblility"",
                    ""type"": ""Button"",
                    ""id"": ""225c51e4-bbc1-40ef-9356-feee0b647b75"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkillShotAbility"",
                    ""type"": ""Button"",
                    ""id"": ""f673ab7c-4d78-496f-a954-40ab5730c5e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ConfirmSkillShotAbility"",
                    ""type"": ""Button"",
                    ""id"": ""00b353b9-1a59-4697-be78-c639eadf7b2e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""dc6cbc6b-b5ae-47fe-990b-1ffad160a229"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectMovePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc78b3dd-b8d0-4454-bd2b-d48364b8c521"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AoeAblility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b668e07a-8e3d-4917-b976-6da7d7c81b14"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillShotAbility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c4733bb6-b470-4ca9-8f63-d045d0d52b1c"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ConfirmSkillShotAbility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GameplayMap
        m_GameplayMap = asset.FindActionMap("GameplayMap", throwIfNotFound: true);
        m_GameplayMap_SelectMovePosition = m_GameplayMap.FindAction("SelectMovePosition", throwIfNotFound: true);
        m_GameplayMap_AoeAblility = m_GameplayMap.FindAction("AoeAblility", throwIfNotFound: true);
        m_GameplayMap_SkillShotAbility = m_GameplayMap.FindAction("SkillShotAbility", throwIfNotFound: true);
        m_GameplayMap_ConfirmSkillShotAbility = m_GameplayMap.FindAction("ConfirmSkillShotAbility", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GameplayMap
    private readonly InputActionMap m_GameplayMap;
    private List<IGameplayMapActions> m_GameplayMapActionsCallbackInterfaces = new List<IGameplayMapActions>();
    private readonly InputAction m_GameplayMap_SelectMovePosition;
    private readonly InputAction m_GameplayMap_AoeAblility;
    private readonly InputAction m_GameplayMap_SkillShotAbility;
    private readonly InputAction m_GameplayMap_ConfirmSkillShotAbility;
    public struct GameplayMapActions
    {
        private @MobalInputActions m_Wrapper;
        public GameplayMapActions(@MobalInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @SelectMovePosition => m_Wrapper.m_GameplayMap_SelectMovePosition;
        public InputAction @AoeAblility => m_Wrapper.m_GameplayMap_AoeAblility;
        public InputAction @SkillShotAbility => m_Wrapper.m_GameplayMap_SkillShotAbility;
        public InputAction @ConfirmSkillShotAbility => m_Wrapper.m_GameplayMap_ConfirmSkillShotAbility;
        public InputActionMap Get() { return m_Wrapper.m_GameplayMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayMapActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayMapActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayMapActionsCallbackInterfaces.Add(instance);
            @SelectMovePosition.started += instance.OnSelectMovePosition;
            @SelectMovePosition.performed += instance.OnSelectMovePosition;
            @SelectMovePosition.canceled += instance.OnSelectMovePosition;
            @AoeAblility.started += instance.OnAoeAblility;
            @AoeAblility.performed += instance.OnAoeAblility;
            @AoeAblility.canceled += instance.OnAoeAblility;
            @SkillShotAbility.started += instance.OnSkillShotAbility;
            @SkillShotAbility.performed += instance.OnSkillShotAbility;
            @SkillShotAbility.canceled += instance.OnSkillShotAbility;
            @ConfirmSkillShotAbility.started += instance.OnConfirmSkillShotAbility;
            @ConfirmSkillShotAbility.performed += instance.OnConfirmSkillShotAbility;
            @ConfirmSkillShotAbility.canceled += instance.OnConfirmSkillShotAbility;
        }

        private void UnregisterCallbacks(IGameplayMapActions instance)
        {
            @SelectMovePosition.started -= instance.OnSelectMovePosition;
            @SelectMovePosition.performed -= instance.OnSelectMovePosition;
            @SelectMovePosition.canceled -= instance.OnSelectMovePosition;
            @AoeAblility.started -= instance.OnAoeAblility;
            @AoeAblility.performed -= instance.OnAoeAblility;
            @AoeAblility.canceled -= instance.OnAoeAblility;
            @SkillShotAbility.started -= instance.OnSkillShotAbility;
            @SkillShotAbility.performed -= instance.OnSkillShotAbility;
            @SkillShotAbility.canceled -= instance.OnSkillShotAbility;
            @ConfirmSkillShotAbility.started -= instance.OnConfirmSkillShotAbility;
            @ConfirmSkillShotAbility.performed -= instance.OnConfirmSkillShotAbility;
            @ConfirmSkillShotAbility.canceled -= instance.OnConfirmSkillShotAbility;
        }

        public void RemoveCallbacks(IGameplayMapActions instance)
        {
            if (m_Wrapper.m_GameplayMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayMapActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayMapActions @GameplayMap => new GameplayMapActions(this);
    public interface IGameplayMapActions
    {
        void OnSelectMovePosition(InputAction.CallbackContext context);
        void OnAoeAblility(InputAction.CallbackContext context);
        void OnSkillShotAbility(InputAction.CallbackContext context);
        void OnConfirmSkillShotAbility(InputAction.CallbackContext context);
    }
}
